package com.build4all.business.domain;

import com.build4all.business.domain.Businesses;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "PendingManagers")
public class PendingManager {

    /* =========================================================
     * PendingManager
     * ---------------------------------------------------------
     * Temporary entity used when a Business invites a manager.
     *
     * Typical flow:
     * 1) Business Owner invites manager by email
     * 2) System creates a PendingManager row with a unique token
     * 3) Email is sent containing the token (invite link)
     * 4) When the manager accepts, you create a real BusinessUser (role=MANAGER)
     * 5) Delete this PendingManager row (or mark it used/expired)
     * ========================================================= */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Primary key generated by DB
    @Column(name = "pending_id")
    private Long id;

    /**
     * Invited manager email (where the invitation is sent).
     * NOTE: not unique here -> same email could be invited multiple times
     * (unless you want to block duplicates per business, then add unique constraint (business_id, email)).
     */
    @Column(nullable = false)
    private String email;

    /**
     * The business that created this invite.
     *
     * Equivalent SQL:
     *   pending_managers.business_id  -> businesses.business_id
     */
    @ManyToOne
    @JoinColumn(name = "business_id", nullable = false)
    private Businesses business;

    /**
     * Unique invitation token used to accept the invite.
     * This is usually a UUID or random secure string.
     *
     * NOTE: unique=true makes it globally unique (good).
     * Also consider adding a DB index on this column for fast lookup.
     */
    @Column(nullable = false, unique = true)
    private String token;

    /**
     * When the invitation row was created.
     * Used to expire old invites (e.g., older than 24h/7d).
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    public PendingManager() {}

    public PendingManager(String email, Businesses business, String token) {
        this.email = email;
        this.business = business;
        this.token = token;
    }

    @PrePersist
    protected void onCreate() {
        // Auto-set createdAt when inserting a new invite
        this.createdAt = LocalDateTime.now();
    }

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Businesses getBusiness() {
        return business;
    }

    public void setBusiness(Businesses business) {
        this.business = business;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
