// src/main/java/com/build4all/admin/dto/AdminAppAssignmentResponse.java
package com.build4all.admin.dto;

import java.time.LocalDate;

/**
 * Response DTO returned to the admin dashboard when listing or viewing app assignments.
 *
 * This DTO represents one "app" under a specific project for an owner/admin (AdminUserProject row),
 * but flattened into simple fields that are easy for the frontend to render.
 *
 * It includes:
 * - Project info (id + name)
 * - App metadata (appName, slug, status)
 * - License validity info (licenseId, validFrom, endTo)
 * - UI config (themeId)
 * - Build artifact URLs (apk/ipa/bundle)
 * - Branding (logoUrl)
 * - Currency display info (currencyCode, currencySymbol)
 */
public class AdminAppAssignmentResponse {

    // The project this app belongs to.
    private Long projectId;
    private String projectName;

    // Display name of the app instance.
    private String appName;

    // URL-friendly identifier used for routing/tenant discovery.
    private String slug;

    // Current status of the assignment (ACTIVE / SUSPENDED / EXPIRED / DELETED).
    private String status;

    // License identifier for this app instance (may be generated by backend).
    private String licenseId;

    // License validity date range.
    private LocalDate validFrom;
    private LocalDate endTo;

    // Theme id chosen for this app instance (nullable => fallback).
    private Long themeId;

    // Build artifact URLs (may be empty if not built yet).
    private String apkUrl;
    private String ipaUrl;

    // <— NEW: additional build artifact URL (e.g., AAB/Web bundle depending on pipeline).
    private String bundleUrl;

    // Public URL for the uploaded logo for this app instance.
    private String logoUrl;

    // Currency code & symbol used by the app (derived from Currency entity if configured).
    private String currencyCode;
    private String currencySymbol;

    public AdminAppAssignmentResponse(
            Long projectId, String projectName, String appName, String slug, String status,
            String licenseId, LocalDate validFrom, LocalDate endTo, Long themeId,
            String apkUrl, String ipaUrl, String bundleUrl, String logoUrl,
            String currencyCode, String currencySymbol) {

        // Assign all values directly (pure DTO with no business logic).
        this.projectId = projectId;
        this.projectName = projectName;
        this.appName = appName;
        this.slug = slug;
        this.status = status;
        this.licenseId = licenseId;
        this.validFrom = validFrom;
        this.endTo = endTo;
        this.themeId = themeId;
        this.apkUrl = apkUrl;
        this.ipaUrl = ipaUrl;
        this.bundleUrl = bundleUrl;
        this.logoUrl = logoUrl;
        this.currencyCode = currencyCode;
        this.currencySymbol = currencySymbol;
    }

    // getters only (or add setters if you need)
    // Getters are enough if this DTO is only used for responses (serialization).
    public Long getProjectId() { return projectId; }
    public String getProjectName() { return projectName; }
    public String getAppName() { return appName; }
    public String getSlug() { return slug; }
    public String getStatus() { return status; }
    public String getLicenseId() { return licenseId; }
    public LocalDate getValidFrom() { return validFrom; }
    public LocalDate getEndTo() { return endTo; }
    public Long getThemeId() { return themeId; }
    public String getApkUrl() { return apkUrl; }
    public String getIpaUrl() { return ipaUrl; }
    public String getBundleUrl() { return bundleUrl; }
    public String getLogoUrl() { return logoUrl; }

    public String getCurrencyCode() { return currencyCode; }
    public String getCurrencySymbol() { return currencySymbol; }
}
