package com.build4all.catalog.domain;

public enum ItemAttributeDataType {
    STRING,   // default: brand, model, color, size...
    NUMBER,   // weight, length, warrantyMonths...
    BOOLEAN   // isWireless, isWaterproof...
}
