package com.build4all.notifications.domain;

public enum FrontNotificationType {
    CHAT_MESSAGE,

    ORDER_CREATED,
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    ORDER_CANCELED_BY_OWNER,
    ORDER_CANCELED_BY_USER,
    ORDER_STATUS_UPDATED,

    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CANCELED_BY_OWNER,
    BOOKING_CANCELED_BY_USER,
    BOOKING_STATUS_UPDATED,

    LOW_STOCK,
    OUT_OF_STOCK,

    REVIEW_RECEIVED,

    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_ISSUED
}